name: PHP Composer

on:
  schedule:
    - cron: "*/1 * * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Update composer
      run: composer update

    - name: Update stats
      run: composer semanal-update
